import { readFileSync, writeFileSync } from 'fs';
const DB = JSON.parse(readFileSync('articles_db.json', 'utf-8'));
const published = DB.filter(a => a.status === 'published').sort((a,b) => new Date(b.date||b.publishedAt) - new Date(a.date||a.publishedAt)).slice(0,20);
const BASE = 'https://td-arabi.com';
let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
xml += '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">\n';
xml += '<channel>\n';
xml += '  <title>TD بالعربي — أخبار التقنية والذكاء الاصطناعي</title>\n';
xml += '  <link>' + BASE + '/</link>\n';
xml += '  <description>جرعتك اليومية من أخبار التقنية والذكاء الاصطناعي</description>\n';
xml += '  <language>ar</language>\n';
xml += '  <lastBuildDate>' + new Date().toUTCString() + '</lastBuildDate>\n';
xml += '  <atom:link href="' + BASE + '/rss.xml" rel="self" type="application/rss+xml"/>\n';
for (const a of published) {
  const title = (a.title || a.title_ar || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const desc = (a.excerpt || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const link = BASE + '/article.html?id=' + encodeURIComponent(a.id);
  const date = new Date(a.date || a.publishedAt).toUTCString();
  const img = a.image_url || a.image || '';
  xml += '  <item>\n';
  xml += '    <title>' + title + '</title>\n';
  xml += '    <link>' + link + '</link>\n';
  xml += '    <guid isPermaLink="true">' + link + '</guid>\n';
  xml += '    <description>' + desc + '</description>\n';
  xml += '    <pubDate>' + date + '</pubDate>\n';
  xml += '    <source url="' + BASE + '/rss.xml">TD بالعربي</source>\n';
  if (img) xml += '    <enclosure url="' + img.replace(/&/g,'&amp;') + '" type="image/jpeg" length="0"/>\n';
  xml += '  </item>\n';
}
xml += '</channel>\n';
xml += '</rss>\n';
writeFileSync('rss.xml', xml, 'utf-8');
console.log('rss.xml written with ' + published.length + ' articles');
